apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vmeh
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0003-tenant/tkrw-pr712-0075-0003-app/devfile-sample-vmeh@sha256:b1a61c8fb36a95eb2421cc268d88bb80c8627791088809101e3dbf3e29dbb0e3
        name: my-nodejs
        resources: {}
status: {}
